version: '3.8'
services:
  typescript-backend-template:
    image: node:14-alpine
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    working_dir: /opt/typescript-backend-template
    volumes:
      - ".:/opt/typescript-backend-template"
    command: npm run start:watch
